### ISSUE TITLE
Path parameters documentation

### ISSUE THREAD

**Issue by SaeeSaadat** [yhttp/yhttp#8]
Since most other similar frameworks call what you're calling `url_parameters`, `path_parameters`, 
please mention it in the documentations to make onboarding smoother for migrating from other frameworks.
```
GET /foo/{PATH_PARAM_1}/bar/{PATH_PARAM_2}
```

also, a good implementation from flask and fastapi is to define the route like this example:
```python
@app.route('/foo/{param1}/bar/{param2})
def get(req, param1, param2):
   ...
```
Although the regex checker might need to change. I don't think the implementation needs to change but it would be nice to be mentioned in the documentation. 

Also please provide an example from testing these path_params using your brilliant `bddrest` framework.

**Comment by pylover** [comment]
Thanks, 

I think the standard regex (current) implementation is enough.

I'll add some more examples in the cookbook.
